### ISSUE TITLE
What software did you use these definitions with?

### ISSUE THREAD

**Issue by marconovino** [ba114/M3.3.1#1]
Sorry that I opened an issue but there seems to be no way to contact you.

**Comment by marconovino** [comment]
I just realized my question wasnt very clear. I meant what software did you use to pull the Bin from the ECU/chip. Did you take out the EEPROM or was this through the OBD1 diagnosis port?

**Comment by Rustle333** [comment]
> I just realized my question wasnt very clear. I meant what software did you use to pull the Bin from the ECU/chip. Did you take out the EEPROM or was this through the OBD1 diagnosis port?

Removed the chip and read with programmer.

**Comment by Rustle333** [comment]
closed - not an actual issue
